Repository sous-chefs/resolver, pull requests merged in 2021-02, with the labels that each got.

#47 Sous Chefs Adoption
  .github/workflows/branchcleanup.yml
  .github/workflows/ci.yml
  .github/workflows/delivery.yml
  .mdlrc
  .travis.yml
  Berksfile
  CHANGELOG.md
  README.md
  kitchen.dokken.yml
  kitchen.exec.yml
  kitchen.yml
  metadata.rb
  spec/unit/recipes/default_spec.rb
  test/integration/cookbooks/resolver-test/metadata.rb
  test/integration/cookbooks/resolver-test/recipes/default.rb
  test/integration/default/inspec/default_spec.rb
Labels: Release: Minor

#48 Port to resources
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  attributes/default.rb
  documentation/resolver_config.md
  documentation/resolver_systemd_resolved_config.md
  kitchen.yml
  libraries/helpers.rb
  libraries/template.rb
  metadata.rb
  recipes/default.rb
  resources/config.rb
  resources/systemd_resolved_config.rb
  spec/unit/recipes/default_spec.rb
  spec/unit/resources/config_spec.rb
  spec/unit/resources/systemd_resolved_config_spec.rb
  templates/default/90-dns-none.conf.erb
  templates/default/resolv.conf.erb
  templates/default/resolved.conf.erb
  test/integration/cookbooks/resolver-test/recipes/default.rb
  test/integration/cookbooks/resolver-test/recipes/systemd_resolved.rb
  test/integration/cookbooks/resolver-test/recipes/test_packages.rb
  test/integration/default/config_spec.rb
  test/integration/default/inspec/default_spec.rb
  test/integration/systemd_resolved/systemd_resolved_spec.rb
Labels: Documentation, Feature Request, Release: Major, Table Flip

#50 Update Chef Infra references
  CHANGELOG.md
  README.md
  templates/default/90-dns-none.conf.erb
  templates/default/resolv.conf.erb
  templates/default/resolved.conf.erb
Labels: Release: Patch

#51 Merge resolv.conf options & remove extra colons
  CHANGELOG.md
  spec/unit/resources/config_spec.rb
  templates/default/resolv.conf.erb
  test/integration/cookbooks/resolver-test/recipes/default.rb
  test/integration/default/config_spec.rb
Labels: Release: Patch

#52 fix blog link for wrapper cookbooks
  CHANGELOG.md
  README.md
Labels: Release: Patch
